### PR TITLE
add export for CreateEmailOptions

### PR DESCRIPTION
**Pull request by JClackett**

### CODE REVIEW

**Comment by MartinXPN** [comment]
Would it be possible to also expose `CreateEmailResponse`?

**Comment by nickfrosty** [comment]
Related: https://github.com/resend/resend-node/issues/122

**Comment by fnielson1** [comment]
Exporting all the types would be great!

**Comment by vcapretz** [comment]
thank you @JClackett for the PR! I opened a new one #396 to work on it, it's going to make sense to end up exporting all request and response interfaces, but we might iterate on exactly how we do it 🙏

**Pull request closed without merging**
